package com.example.game_list.enums

enum class GameGenre(val displayName: String) {
    MMO("MMO"),
    MMORPG("MMORPG"),
    SHOOTER("Shooter"),
    STRATEGY("Strategy"),
    MOBA("Moba"),
    CARD_GAMES("Card Games"),
    RACING("Racing"),
    SPORTS("Sports"),
    SOCIAL("Social"),
    FIGHTING("Fighting"),
    MMOFPS("MMOFPS"),
    ACTION_RPG("Action RPG"),
    SANDBOX("Sandbox"),
    OPEN_WORLD("Open World"),
    SURVIVAL("Survival"),
    BATTLE_ROYALE("Battle Royale"),
    MMOTPS("MMOTPS"),
    ANIME("Anime"),
    PVP("PvP"),
    PVE("PvE"),
    PIXEL("Pixel"),
    MMORTS("MMORTS"),
    FANTASY("Fantasy"),
    SCI_FI("Sci-Fi"),
    ACTION("Action"),
    VOXEL("Voxel"),
    ZOMBIE("Zombie"),
    TURN_BASED("Turn-Based"),
    FIRST_PERSON_VIEW("First Person View"),
    THIRD_PERSON_VIEW("Third Person View"),
    TOP_DOWN_VIEW("Top-Down View");
}